-- ChemFarm Top-Down Showdown
-- Run this file first in the Supabase SQL editor.

create extension if not exists pgcrypto;

create table if not exists public.chemfarm_rooms (
  id uuid primary key default gen_random_uuid(),
  code varchar(6) not null unique check (code ~ '^[0-9]{6}$'),
  qr_url text,
  status text not null default 'lobby' check (status in ('lobby', 'playing', 'finished')),
  started_at timestamptz,
  ends_at timestamptz,
  host_player_id uuid,
  created_at timestamptz not null default now()
);

-- CREATE TABLE IF NOT EXISTS does not add new columns to an older table.
-- These additive migrations make this script safe to rerun after a partial or
-- earlier ChemFarm schema installation.
alter table public.chemfarm_rooms add column if not exists qr_url text;
alter table public.chemfarm_rooms add column if not exists status text not null default 'lobby';
alter table public.chemfarm_rooms add column if not exists started_at timestamptz;
alter table public.chemfarm_rooms add column if not exists ends_at timestamptz;
alter table public.chemfarm_rooms add column if not exists host_player_id uuid;
alter table public.chemfarm_rooms add column if not exists created_at timestamptz not null default now();

create table if not exists public.chemfarm_players (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.chemfarm_rooms(id) on delete cascade,
  nickname varchar(20) not null check (char_length(trim(nickname)) between 1 and 20),
  cash integer not null default 100 check (cash >= 0),
  fertilizer_s_count integer not null default 0 check (fertilizer_s_count >= 0),
  fertilizer_a_count integer not null default 0 check (fertilizer_a_count >= 0),
  crops_harvested integer not null default 0,
  quizzes_solved integer not null default 0,
  best_quiz_time_ms integer,
  is_ready boolean not null default false,
  is_host boolean not null default false,
  joined_at timestamptz not null default now()
);

alter table public.chemfarm_players add column if not exists cash integer not null default 100;
alter table public.chemfarm_players add column if not exists fertilizer_s_count integer not null default 0;
alter table public.chemfarm_players add column if not exists fertilizer_a_count integer not null default 0;
alter table public.chemfarm_players add column if not exists crops_harvested integer not null default 0;
alter table public.chemfarm_players add column if not exists quizzes_solved integer not null default 0;
alter table public.chemfarm_players add column if not exists best_quiz_time_ms integer;
alter table public.chemfarm_players add column if not exists is_ready boolean not null default false;
alter table public.chemfarm_players add column if not exists is_host boolean not null default false;
alter table public.chemfarm_players add column if not exists joined_at timestamptz not null default now();

alter table public.chemfarm_rooms
  drop constraint if exists rooms_host_player_id_fkey;
alter table public.chemfarm_rooms
  add constraint rooms_host_player_id_fkey
  foreign key (host_player_id) references public.chemfarm_players(id) on delete set null;

create table if not exists public.chemfarm_quiz_questions (
  id uuid primary key default gen_random_uuid(),
  type text not null check (type in ('rate_table', 'energy_graph')),
  question_data jsonb not null,
  answer jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.chemfarm_quiz_attempts (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null references public.chemfarm_players(id) on delete cascade,
  question_id uuid not null references public.chemfarm_quiz_questions(id) on delete cascade,
  is_correct boolean not null,
  response_time_ms integer not null check (response_time_ms >= 0),
  grade_earned text check (grade_earned in ('S', 'A') or grade_earned is null),
  submitted_answer jsonb,
  created_at timestamptz not null default now()
);

alter table public.chemfarm_quiz_attempts add column if not exists submitted_answer jsonb;

create table if not exists public.chemfarm_game_events (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.chemfarm_rooms(id) on delete cascade,
  player_id uuid references public.chemfarm_players(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists chemfarm_players_room_id_idx on public.chemfarm_players(room_id);
create index if not exists chemfarm_quiz_attempts_player_id_idx on public.chemfarm_quiz_attempts(player_id);
create index if not exists chemfarm_game_events_room_id_created_at_idx on public.chemfarm_game_events(room_id, created_at desc);

alter table public.chemfarm_rooms enable row level security;
alter table public.chemfarm_players enable row level security;
alter table public.chemfarm_quiz_questions enable row level security;
alter table public.chemfarm_quiz_attempts enable row level security;
alter table public.chemfarm_game_events enable row level security;

drop policy if exists "rooms are available to game clients" on public.chemfarm_rooms;
create policy "rooms are available to game clients" on public.chemfarm_rooms for all to anon, authenticated using (true) with check (true);
drop policy if exists "players are available within rooms" on public.chemfarm_players;
create policy "players are available within rooms" on public.chemfarm_players for all to anon, authenticated using (true) with check (true);
drop policy if exists "questions are readable" on public.chemfarm_quiz_questions;
create policy "questions are readable" on public.chemfarm_quiz_questions for select to anon, authenticated using (true);
drop policy if exists "attempts can be recorded" on public.chemfarm_quiz_attempts;
create policy "attempts can be recorded" on public.chemfarm_quiz_attempts for insert to anon, authenticated with check (true);
drop policy if exists "attempts are readable" on public.chemfarm_quiz_attempts;
create policy "attempts are readable" on public.chemfarm_quiz_attempts for select to anon, authenticated using (true);
drop policy if exists "events are available to game clients" on public.chemfarm_game_events;
create policy "events are available to game clients" on public.chemfarm_game_events for all to anon, authenticated using (true) with check (true);

create or replace function public.get_server_time()
returns timestamptz
language sql
volatile
security definer
set search_path = public
as $$ select clock_timestamp(); $$;

create or replace function public.start_game(target_room_id uuid)
returns setof public.chemfarm_rooms
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  update public.chemfarm_rooms
  set status = 'playing',
      started_at = clock_timestamp(),
      ends_at = clock_timestamp() + interval '5 minutes'
  where id = target_room_id and status = 'lobby'
  returning *;
end;
$$;

create or replace function public.reset_room(target_room_id uuid)
returns setof public.chemfarm_rooms
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.chemfarm_players
  set cash = 100,
      fertilizer_s_count = 0,
      fertilizer_a_count = 0,
      crops_harvested = 0,
      quizzes_solved = 0,
      best_quiz_time_ms = null,
      is_ready = is_host
  where room_id = target_room_id;

  return query
  update public.chemfarm_rooms
  set status = 'lobby', started_at = null, ends_at = null
  where id = target_room_id
  returning *;
end;
$$;

grant execute on function public.get_server_time() to anon, authenticated;
grant execute on function public.start_game(uuid) to anon, authenticated;
grant execute on function public.reset_room(uuid) to anon, authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'chemfarm_rooms'
  ) then alter publication supabase_realtime add table public.chemfarm_rooms; end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'chemfarm_players'
  ) then alter publication supabase_realtime add table public.chemfarm_players; end if;
end $$;
